# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Zac/Desktop/EE214Project_7Challenge/EE214_project7_challenge/EE214_project7_challenge.cache/wt [current_project]
set_property parent.project_path C:/Users/Zac/Desktop/EE214Project_7Challenge/EE214_project7_challenge/EE214_project7_challenge.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/Zac/Desktop/EE214Project_7Challenge/EE214_project7_challenge/EE214_project7_challenge.srcs/sources_1/new/stopwatch.v
read_xdc C:/Users/Zac/Desktop/EE214Project_7Challenge/EE214_project7_challenge/EE214_project7_challenge.srcs/constrs_1/imports/NexysDDRMasterFile/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Zac/Desktop/EE214Project_7Challenge/EE214_project7_challenge/EE214_project7_challenge.srcs/constrs_1/imports/NexysDDRMasterFile/Nexys4DDR_Master.xdc]

catch { write_hwdef -file stop_watch.hwdef }
synth_design -top stop_watch -part xc7a100tcsg324-1
write_checkpoint -noxdef stop_watch.dcp
catch { report_utilization -file stop_watch_utilization_synth.rpt -pb stop_watch_utilization_synth.pb }
